### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by debiansid** [rnetx/sing-box#44]
### Operating system

Windows

### System version

11

### Installation type

Original sing-box Command Line

### Version

```shell
sing-box version 1.10.0-alpha.20

Environment: go1.22.4 windows/amd64
Tags: with_gvisor,with_quic,with_clash_api,with_utls,with_outbound_provider
Revision: df8f5d8eea3cd12879892d7d7c4ded6c3a9f8e1b
CGO: enabled

```

### Description

```
D:\sing-box>sing-box-windows-amd64-v3.exe -c config-next2.json -D d:\sing-box run
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/sagernet/sing-box/outbound.(*Selector).Start(0xc000271000)
        github.com/sagernet/sing-box/outbound/selector.go:157 +0x94b
github.com/sagernet/sing-box.(*Box).startOutbounds(0xc00037ae60)
        github.com/sagernet/sing-box/box_outbound.go:52 +0x7d4
github.com/sagernet/sing-box.(*Box).preStart(0xc00037ae60)
        github.com/sagernet/sing-box/box.go:271 +0x79b
github.com/sagernet/sing-box.(*Box).start(0xc00037ae60)
        github.com/sagernet/sing-box/box.go:279 +0x2a
github.com/sagernet/sing-box.(*Box).Start(0xc00037ae60)
        github.com/sagernet/sing-box/box.go:221 +0x36
main.create()
        github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:160 +0x472
main.run()
        github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:174 +0x10c
main.init.func26(0xc0001bbb00?, {0x190bd5d?, 0x4?, 0x190bd61?})
        github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:30 +0x17
github.com/spf13/cobra.(*Command).execute(0x243ec80, {0xc000134800, 0x4, 0x4})
        github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x243ef60)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        github.com/sagernet/sing-box/cmd/sing-box/main.go:38 +0x1e
```

### Reproduction

f confidence in my own intelligence.

**Comment by 0xffffharry** [comment]
请尝试最新commit

**Comment by debiansid** [comment]
最新commit

```log
D:\sing-box>sing-box-windows-amd64-v3.exe -c config-next2.json -D d:\sing-box run
panic: runtime error: slice bounds out of range [20:18]

goroutine 1 [running]:
github.com/sagernet/sing-box/common/outboundprovider/action.(*actionFilter).execute(0xc00007c930, {0xc00028bbb0?, 0xab1fbc?}, {0xb4662e?, 0xc19b9b0f2bcc1b38?}, {0x1b1bea8, 0xc00022ef90}, 0xc000325680)
        github.com/sagernet/sing-box/common/outboundprovider/action/action_filter.go:49 +0x7de
github.com/sagernet/sing-box/common/outboundprovider/action.(*ProviderActionGroup).Execute(0xc00022efa8, {0x1b0c5c8, 0xc000241e90}, {0x1b249b0, 0xc000232908}, {0x1b1bea8, 0xc00022ef90}, {0xc000300280, 0x14, 0x14})
        github.com/sagernet/sing-box/common/outboundprovider/action/action.go:61 +0x18b
github.com/sagernet/sing-box/outbound.(*Provider).start(0xc000073dc0)
        github.com/sagernet/sing-box/outbound/provider.go:317 +0x369
github.com/sagernet/sing-box/outbound.(*Provider).lazyStart.func1()
        github.com/sagernet/sing-box/outbound/provider.go:417 +0x1c
sync.(*Once).doSlow(0xc00008c378?, 0xc00028eef0?)
        sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        sync/once.go:65
github.com/sagernet/sing-box/outbound.(*Provider).lazyStart(0xc000073dc0)
        github.com/sagernet/sing-box/outbound/provider.go:416 +0x4a
github.com/sagernet/sing-box/outbound.(*Provider).Start(0xc0001b7b1b?)
        github.com/sagernet/sing-box/outbound/provider.go:423 +0x13
github.com/sagernet/sing-box.(*Box).startOutbounds(0xc00031efa0)
        github.com/sagernet/sing-box/box_outbound.go:52 +0x7d4
github.com/sagernet/sing-box.(*Box).preStart(0xc00031efa0)
        github.com/sagernet/sing-box/box.go:271 +0x79b
github.com/sagernet/sing-box.(*Box).start(0xc00031efa0)
        github.com/sagernet/sing-box/box.go:279 +0x2a
github.com/sagernet/sing-box.(*Box).Start(0xc00031efa0)
        github.com/sagernet/sing-box/box.go:221 +0x36
main.create()
        github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:160 +0x472
main.run()
        github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:174 +0x10c
main.init.func26(0xc000113b00?, {0x192bd5d?, 0x4?, 0x192bd61?})
        github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:30 +0x17
github.com/spf13/cobra.(*Command).execute(0x245fc80, {0xc00008a840, 0x4, 0x4})
        github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x245ff60)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
        github.com/sagernet/sing-box/cmd/sing-box/main.go:38 +0x1e
```
